# Generated by Django 3.1 on 2020-08-17 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extract_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='extract',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracts', to='api.account'),
        ),
    ]
